[package]
name = "cwillsey/rbx-repo-template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
component = "sleitnick/component@2.4.3"
signal = "sleitnick/signal@1.1.0"
promise = "evaera/promise@3.2.1"
trove = "sleitnick/trove@0.3.0"
shake = "sleitnick/shake@0.1.4"
knit = "sleitnick/knit@1.4.3"